services:
  envio-postgres:
    image: postgres:16
    restart: always
    # La section "ports" a été supprimée pour empêcher l'accès extérieur à la base de données.
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${ENVIO_POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${ENVIO_PG_USER:-postgres}
      POSTGRES_DB: ${ENVIO_PG_DATABASE:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ENVIO_PG_USER:-postgres} -d ${ENVIO_PG_DATABASE:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-proxy-net

  graphql-engine:
    image: hasura/graphql-engine:v2.23.0
    ports:
      - "${HASURA_EXTERNAL_PORT:-8080}:8080"
    depends_on:
      envio-postgres:
        condition: service_healthy
    restart: always
    volumes:
      - ./generated/hasura/migrations:/hasura/migrations
      - ./generated/hasura/metadata:/hasura/metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${ENVIO_PG_USER:-postgres}:${ENVIO_POSTGRES_PASSWORD:-postgres}@envio-postgres:5432/${ENVIO_PG_DATABASE:-postgres}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET:-myadminsecretkey}
      # --- Modifications pour la Production ---
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # Désactive la console Hasura, plus sécurisé.
      HASURA_GRAPHQL_CORS_DOMAIN: "*" # Remplacez par vos domaines frontend.
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - my-proxy-net

  envio-indexer:
    container_name: envio-indexer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${INDEXER_EXTERNAL_PORT:-8081}:8081"
    depends_on:
      graphql-engine:
        condition: service_healthy
    restart: always
    environment:
      # Ces variables sont injectées depuis votre gestionnaire de secrets en production
      ENVIO_POSTGRES_PASSWORD: ${ENVIO_POSTGRES_PASSWORD}
      ENVIO_PG_HOST: envio-postgres
      ENVIO_PG_PORT: 5432
      ENVIO_PG_USER: ${ENVIO_PG_USER}
      ENVIO_PG_DATABASE: ${ENVIO_PG_DATABASE}
      HASURA_GRAPHQL_URL: http://graphql-engine:8080
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      CONFIG_FILE: ${CONFIG_FILE:-config.yaml}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    networks:
      - my-proxy-net

volumes:
  db_data:

networks:
  my-proxy-net:
    name: local_test_network
